### ISSUE TITLE
RSIllegalArgumentException: Radius out of range (0 < r <= 25)

### ISSUE THREAD

**Issue by AlaaZarifa** [vipulasri/TicketView#33]
**I'm using it in a RecyclerView and it crashes the app with this error?**
 
```
 android.renderscript.RSIllegalArgumentException: Radius out of range (0 < r <= 25).
        at android.renderscript.ScriptIntrinsicBlur.setRadius(ScriptIntrinsicBlur.java:82)
        at com.vipulasri.ticketview.BlurBuilder.blur(BlurBuilder.java:20)
        at com.vipulasri.ticketview.TicketView.generateShadow(TicketView.java:281)
        at com.vipulasri.ticketview.TicketView.doLayout(TicketView.java:262)
        at com.vipulasri.ticketview.TicketView.onDraw(TicketView.java:111)
```

> [**Full logcat error in this gist**
> ](https://gist.github.com/AlaaZarifa/84068d874d85298562c94d64b7f82d57)

**Here's the TicketView I'm using**
it shows perfectly fine in the preview btw.

```
 <com.vipulasri.ticketview.TicketView
        android:id="@+id/ticketView"
        android:layout_width="match_parent"
        android:layout_height="250dp"
        android:layout_marginHorizontal="16dp"
        android:layout_marginVertical="5dp"
        app:ticketBackgroundColor="@color/white"
        app:ticketCornerRadius="10dp"
        app:ticketCornerType="rounded"
        app:ticketDividerColor="#D9D9D9"
        app:ticketDividerDashGap="6dp"
        app:ticketDividerDashLength="8dp"
        app:ticketDividerPadding="5dp"
        app:ticketDividerType="dash"
        app:ticketDividerWidth="1dp"
        app:ticketElevation="3dp"
        app:ticketOrientation="horizontal"
        app:ticketScallopPositionPercent="77"
        app:ticketScallopRadius="10dp"
        app:ticketShadowColor="@color/black"
        app:ticketShowBorder="false"
        app:ticketShowDivider="true" />
```

**Comment by vipulasri** [comment]
@AlaaZarifa which android OS you are running this on? 
Have you tried the view alone (not in RecyclerView)?

**Comment by AlaaZarifa** [comment]
@vipulasri I just tried it without RecyclerViewand still the same crash.
I'm using it on Android 10 on Xiaomi Pocophone F1

**Comment by vipulasri** [comment]
@AlaaZarifa can you try the latest version: `1.1.2`?

**Comment by AlaaZarifa** [comment]
@vipulasri I just did and no crash occurred 👍
