### ISSUE TITLE
Render Problem

### ISSUE THREAD

**Issue by EduardoRicardez** [vipulasri/TicketView#4]
I have this Render Problem in the xml, i cant see the example of ticketview in the preview mode

java.lang.NoClassDefFoundError: Could not initialize class android.renderscript.RenderScript
	at com.vipulasri.ticketview.TicketView.generateShadow(TicketView.java:272)
	at com.vipulasri.ticketview.TicketView.doLayout(TicketView.java:254)
	at com.vipulasri.ticketview.TicketView.onDraw_Original(TicketView.java:110)
	at com.vipulasri.ticketview.TicketView.onDraw(TicketView.java)
	at android.view.View.draw(View.java:19156)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:541)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:760)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vipulasri** [comment]
Yeah, I know that's an issue. I have to look a way around to improve its rendering in edit mode.

**Comment by vipulasri** [comment]
Fixed in [c46d4c1](https://github.com/vipulasri/TicketView/commit/02857c46d4c19f987005795df94e98b88932b9a7)
